sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 120.26.140.240
    port: 3306
    database: sky_take_out
    username: javaboniu
    password: Qcb258036!
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tHzX4fMjySKcCoCvYci
    access-key-secret: vPKhVa4Kux8jUP6fU4614CQ3FW0wiC
    bucket-name: cangqiongwaimaipbj